const Map<String, List<String>> ecuadorLocations = {
  'Pichincha': ['Quito', 'Cayambe', 'Rumiñahui'],
  'Guayas': ['Guayaquil', 'Daule', 'Samborondón'],
  'Azuay': ['Cuenca', 'Gualaceo', 'Paute'],
  'Imbabura': ['Ibarra', 'Otavalo', 'Cotacachi', 'Antonio Ante', 'Urcuquí'],
  'Manabí': ['Portoviejo', 'Manta', 'Montecristi'],
  'El Oro': ['Machala', 'Pasaje', 'Santa Rosa'],
  'Loja': ['Loja', 'Vilcabamba', 'Catamayo'],
  'Carchi': ['Tulcán', 'San Gabriel', 'Mira'],
  'Esmeraldas': ['Esmeraldas', 'Atacames', 'Quinindé'],
  'Chimborazo': ['Riobamba', 'Guano', 'Alausí'],
  'Cotopaxi': ['Latacunga', 'Pujilí', 'Salcedo'],
  'Tungurahua': ['Ambato', 'Baños', 'Pelileo'],
  'Bolívar': ['Guaranda', 'Echeandía', 'San Miguel'],
  'Los Ríos': ['Babahoyo', 'Quevedo', 'Ventanas'],
  'Sucumbíos': ['Nueva Loja (Lago Agrio)', 'Shushufindi', 'Cascales'],
  'Orellana': ['Francisco de Orellana (Coca)', 'Loreto', 'Dayuma'],
  'Pastaza': ['Puyo', 'Santa Clara', 'Arajuno'],
  'Morona Santiago': ['Macas', 'Gualaquiza', 'Santiago'],
  'Zamora Chinchipe': ['Zamora', 'Yantzaza', 'Nambija'],
  'Galápagos': ['Puerto Ayora', 'Puerto Baquerizo Moreno', 'Villamil'],
};
